---
- name: Basic instance setup
  hosts: watchtower
  become: true
  gather_facts: false

  tasks:
    - name: Update local index
      ansible.builtin.command: "apt update"

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - vim
          - mtr
        state: present



- name: Configure fail2ban
  hosts: watchtower
  gather_facts: false
  tasks:

